# Generated by Django 4.0.3 on 2022-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_alter_suggestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='title',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='aadhar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='contact',
            field=models.TextField(null=True),
        ),
    ]
