# Generated by Django 4.0.3 on 2022-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='title',
        ),
        migrations.AddField(
            model_name='complaint',
            name='aadhar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
