# Generated by Django 4.0.3 on 2022-07-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcements_title_announcements_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='user',
        ),
        migrations.AddField(
            model_name='announcements',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='announcements',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.TextField(null=True),
        ),
    ]
