# Generated by Django 4.0.3 on 2022-07-28 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='aadhar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
