# Generated by Django 4.0.3 on 2022-07-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_citizen_aadhar_alter_citizen_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='profile_pic',
        ),
    ]
